version: '3.3'
services:
    gui:
        image: epinux/kluster:latest
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - DISPLAY=$DISPLAY
        command: /usr/bin/python3 -m HSTB.kluster
        ports:
            - 44683:44683
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ~/.Xauthority:/root/.Xauthority
        network_mode: "host"
